// ROLE-06 — Tokens de protocolo preservados byte a byte (imutáveis, sem enum).

export const PROTOCOL_TOKENS = {
  INVALID_ORCHESTRATOR_CONTEXT: 'INVALID_ORCHESTRATOR_CONTEXT',
  AGENT_ROUTING_REQUIRED: 'AGENT_ROUTING_REQUIRED',
  INVALID_AGENT_ROUTING: 'INVALID_AGENT_ROUTING',
  AGENT_ROUTING_PASS: 'AGENT_ROUTING_PASS',
  'AGENT_OK:<agente>': 'AGENT_OK:<agente>',
  BLOCKED_NEEDS_HUMAN: 'BLOCKED_NEEDS_HUMAN',
  READY_FOR_HUMAN_REVIEW: 'READY_FOR_HUMAN_REVIEW',
  MAX_ITERATIONS_REACHED: 'MAX_ITERATIONS_REACHED',
  FAILED_QUALITY_GATES: 'FAILED_QUALITY_GATES',
  NO_TEST_RUNNER_DECLARED: 'NO_TEST_RUNNER_DECLARED',
} as const;

export const AGENT_OK_PREFIX = 'AGENT_OK:';

export const TERMINAL_STATE_TOKENS = [
  'READY_FOR_HUMAN_REVIEW',
  'BLOCKED_NEEDS_HUMAN',
  'MAX_ITERATIONS_REACHED',
  'FAILED_QUALITY_GATES',
] as const;

export function agentOkToken(agent: string): string {
  return `${AGENT_OK_PREFIX}${agent}`;
}
